/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/all-courses` | `/all-courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/create-course` | `/create-course`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/enrolled-courses` | `/enrolled-courses`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(main)'}/[courseId]` | `/[courseId]`, params: Router.UnknownInputParams & { courseId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/all-courses` | `/all-courses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/create-course` | `/create-course`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/enrolled-courses` | `/enrolled-courses`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(main)'}/[courseId]` | `/[courseId]`, params: Router.UnknownOutputParams & { courseId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/all-courses${`?${string}` | `#${string}` | ''}` | `/all-courses${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/create-course${`?${string}` | `#${string}` | ''}` | `/create-course${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/enrolled-courses${`?${string}` | `#${string}` | ''}` | `/enrolled-courses${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/all-courses` | `/all-courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/create-course` | `/create-course`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/enrolled-courses` | `/enrolled-courses`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(main)'}/[courseId]` | `/[courseId]`, params: Router.UnknownInputParams & { courseId: string | number; } };
    }
  }
}
